version: '3.8'

services:
  db:
    image: postgres:15
    container_name: health_dwh_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Scheduling durch Apache Airflow
  airflow-init:
    image: apache/airflow:2.8.1
    container_name: health_dwh_airflow_init
    depends_on:
      db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./etl_pipeline/dags:/opt/airflow/dags
      - ./etl_pipeline:/opt/airflow/etl_pipeline
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com
      "

  airflow:
    image: apache/airflow:2.8.1
    container_name: health_dwh_airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./etl_pipeline/dags:/opt/airflow/dags
      - ./etl_pipeline:/opt/airflow/etl_pipeline
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow scheduler &
      airflow webserver
      "


volumes:
  postgres_data: